title: "Geek with a Beer"
description: "Give me a beer to drink, and I shall move your cloud."



# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/tale"
url:            "https://chesterhow.github.io"

# Build settings
remote_theme: chesterhow/tale
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
