# Site settings
title: "Geek with a Beer"
description: "Give me a beer to drink, and I shall move your cloud."
baseurl:        "/"
url:            "https://geekwithabeer.github.io"

# Build settings
remote_theme: chesterhow/tale
markdown:       kramdown
include:
  - _pages

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
