# title: 
# description: "Give me a beer to drink, and I shall move your cloud."

# Mandatory settings

blog_theme: dark # Or use light
name: "Geek with a Beer"
paginate: 10
url: "geekwithabeer.github.io " # add your site url (format: https://example.com)

remote_theme: nielsenramon/chalk
